name = "kes-api"
main = "build/worker/shim.mjs"
compatibility_date = "2024-11-20"

[build]
command = "cargo install -q worker-build && worker-build --release"

[[d1_databases]]
binding = "DB"
database_name = "kes-d1"
database_id = "c13735ee-3484-494e-8e94-e95ee15fda8d"
